/**
 * Tokens de injeção de dependência para o módulo admin
 */

// Use Cases - Admin Users
export const LIST_ADMIN_USERS_USECASE = Symbol('LIST_ADMIN_USERS_USECASE');
export const CREATE_ADMIN_USER_USECASE = Symbol('CREATE_ADMIN_USER_USECASE');
export const UPDATE_ADMIN_USER_USECASE = Symbol('UPDATE_ADMIN_USER_USECASE');
export const REMOVE_ADMIN_USER_USECASE = Symbol('REMOVE_ADMIN_USER_USECASE');

// Use Cases - Validations
export const LIST_VALIDATIONS_USECASE = Symbol('LIST_VALIDATIONS_USECASE');
export const CREATE_VALIDATION_USECASE = Symbol('CREATE_VALIDATION_USECASE');
export const UPDATE_VALIDATION_USECASE = Symbol('UPDATE_VALIDATION_USECASE');
export const REMOVE_VALIDATION_USECASE = Symbol('REMOVE_VALIDATION_USECASE');

// Use Cases - Payment Types
export const LIST_PAYMENT_TYPES_USECASE = Symbol('LIST_PAYMENT_TYPES_USECASE');
export const CREATE_PAYMENT_TYPE_USECASE = Symbol('CREATE_PAYMENT_TYPE_USECASE');
export const UPDATE_PAYMENT_TYPE_USECASE = Symbol('UPDATE_PAYMENT_TYPE_USECASE');
export const REMOVE_PAYMENT_TYPE_USECASE = Symbol('REMOVE_PAYMENT_TYPE_USECASE');

// Use Cases - Certificate Types
export const LIST_CERTIFICATE_TYPES_USECASE = Symbol('LIST_CERTIFICATE_TYPES_USECASE');
export const CREATE_CERTIFICATE_TYPE_USECASE = Symbol('CREATE_CERTIFICATE_TYPE_USECASE');
export const UPDATE_CERTIFICATE_TYPE_USECASE = Symbol('UPDATE_CERTIFICATE_TYPE_USECASE');
export const REMOVE_CERTIFICATE_TYPE_USECASE = Symbol('REMOVE_CERTIFICATE_TYPE_USECASE');

// Use Cases - Certificate Status
export const LIST_CERTIFICATE_STATUS_USECASE = Symbol('LIST_CERTIFICATE_STATUS_USECASE');
export const FIND_CERTIFICATE_STATUS_BY_ID_USECASE = Symbol(
  'FIND_CERTIFICATE_STATUS_BY_ID_USECASE',
);
export const FIND_CERTIFICATE_STATUS_BY_NAME_USECASE = Symbol(
  'FIND_CERTIFICATE_STATUS_BY_NAME_USECASE',
);
export const CREATE_CERTIFICATE_STATUS_USECASE = Symbol('CREATE_CERTIFICATE_STATUS_USECASE');
export const UPDATE_CERTIFICATE_STATUS_USECASE = Symbol('UPDATE_CERTIFICATE_STATUS_USECASE');
export const REMOVE_CERTIFICATE_STATUS_USECASE = Symbol('REMOVE_CERTIFICATE_STATUS_USECASE');

// Use Cases - Certificate Status Validations
export const LIST_STATUS_VALIDATIONS_USECASE = Symbol('LIST_STATUS_VALIDATIONS_USECASE');
export const CREATE_STATUS_VALIDATION_USECASE = Symbol('CREATE_STATUS_VALIDATION_USECASE');
export const UPDATE_STATUS_VALIDATION_USECASE = Symbol('UPDATE_STATUS_VALIDATION_USECASE');
export const REMOVE_STATUS_VALIDATION_USECASE = Symbol('REMOVE_STATUS_VALIDATION_USECASE');

// Use Cases - Certificate Tags
export const LIST_TAGS_USECASE = Symbol('LIST_TAGS_USECASE');
export const CREATE_TAG_USECASE = Symbol('CREATE_TAG_USECASE');
export const UPDATE_TAG_USECASE = Symbol('UPDATE_TAG_USECASE');
export const REMOVE_TAG_USECASE = Symbol('REMOVE_TAG_USECASE');
export const ASSIGN_TAG_USECASE = Symbol('ASSIGN_TAG_USECASE');
export const UNASSIGN_TAG_USECASE = Symbol('UNASSIGN_TAG_USECASE');
export const UPDATE_CERTIFICATE_TAGS_USECASE = Symbol('UPDATE_CERTIFICATE_TAGS_USECASE');

// Use Cases - Reports
export const GET_REPORT_METRICS_USECASE = Symbol('GET_REPORT_METRICS_USECASE');
export const GET_REPORT_CERTIFICATES_USECASE = Symbol('GET_REPORT_CERTIFICATES_USECASE');
